/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package component;

import event.EventMenuSelected;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import model.ModelMenu;
import model.ModelUser;

/**
 *
 * @author usER
 */
public class Menu extends javax.swing.JPanel {

    /**
     * Creates new form Menu
     */
    private EventMenuSelected event;

    public void addEventMenuSelected(EventMenuSelected event) {
        this.event = event;
        listMenu.addEventMenuSelected(event);
    }
    public Menu() {
        initComponents();
        setOpaque(false);
        listMenu.setOpaque(false);
    }
    
    public void initiation(ModelUser modelUser) {
        if(modelUser.getLevel().equals("Owner")) {
            listMenu.addItem(new ModelMenu("dashboard", "Dashobard", ModelMenu.MenuType.MENU));
            listMenu.addItem(new ModelMenu("", "", ModelMenu.MenuType.EMPTY));
            listMenu.addItem(new ModelMenu("", "Master Data", ModelMenu.MenuType.TITLE));
            listMenu.addItem(new ModelMenu("checklist", "Layanan", ModelMenu.MenuType.MENU));
            listMenu.addItem(new ModelMenu("check", "Customer", ModelMenu.MenuType.MENU));
            listMenu.addItem(new ModelMenu("group", "Karyawan", ModelMenu.MenuType.MENU));
            listMenu.addItem(new ModelMenu("user", "Pengguna", ModelMenu.MenuType.MENU));
            listMenu.addItem(new ModelMenu("", "", ModelMenu.MenuType.EMPTY));    
        }
        listMenu.addItem(new ModelMenu("bill", "Transaksi", ModelMenu.MenuType.MENU));
        listMenu.addItem(new ModelMenu("", "", ModelMenu.MenuType.EMPTY));
        listMenu.addItem(new ModelMenu("", "Lain - lain", ModelMenu.MenuType.TITLE));
        listMenu.addItem(new ModelMenu("coupon", "Buat Voucher", ModelMenu.MenuType.MENU));
        listMenu.addItem(new ModelMenu("report", "Laporan", ModelMenu.MenuType.MENU));
    }
    
    protected void paintChildren(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#AA03CC"), 0, getHeight(), Color.decode("#9502b3"));
        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
        g2.fillRect(getWidth() - 20, 0, getWidth(), getHeight());
        super.paintChildren(grphcs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogo = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        listMenu = new swing.ListMenu<>();

        panelLogo.setOpaque(false);

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logo.setText("SALON PUTRI");

        logo1.setBackground(new java.awt.Color(255, 255, 255));
        logo1.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        logo1.setForeground(new java.awt.Color(255, 255, 255));
        logo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lotus.png"))); // NOI18N

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(logo1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(listMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ListMenu<String> listMenu;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    private javax.swing.JPanel panelLogo;
    // End of variables declaration//GEN-END:variables
}
