/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package features;
import control.ControlLayanan;
import event.TableEvent;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.border.EmptyBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.ModelHeaderTable;
import model.ModelJenisLayanan;
import model.ModelLayanan;
import model.ModelRenderTable;
import swing.TableCellEditor;
import swing.TableCellEventRender;

/**
 *
 * @author usER
 */
public class Layanan extends javax.swing.JPanel {

    /**
     * Creates new form Transaksi
     */
    private TableEvent event;
    private DefaultTableModel tabmodel1;
    private TableRowSorter<DefaultTableModel> tableRowSorter1;
    private ControlLayanan controlLayanan = new ControlLayanan();
    public Layanan() {
        initComponents();
        txtIdLayanan.setText(controlLayanan.autoID());
        styleTable(scrollTableData, tableData, 6);
        tabmodel1 = (DefaultTableModel) tableData.getModel();
        tableRowSorter1 = new TableRowSorter<>(tabmodel1);
        tableData.setRowSorter(tableRowSorter1);
        enableField();
        tampilDataTable();
        eventTable();
        cariDataTable();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelData = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelForm = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtIdLayanan = new javax.swing.JTextField();
        txtTipeLayanan = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        txtIdJenisLayanan = new javax.swing.JTextField();
        btnPilihJenis = new javax.swing.JButton();
        txtJenisLayanan = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        panelTable = new javax.swing.JPanel();
        scrollTableData = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        panelData.setBackground(new java.awt.Color(185, 185, 185));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(149, 2, 179));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LAYANAN");
        jLabel1.setOpaque(true);

        panelForm.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("ID Jenis Layanan");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Jenis Layanan");

        jLabel16.setBackground(new java.awt.Color(149, 2, 179));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Tambah Layanan");
        jLabel16.setOpaque(true);

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Tipe Layanan");

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("ID Layanan");

        txtIdLayanan.setBackground(new java.awt.Color(255, 255, 255));
        txtIdLayanan.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtIdLayanan.setForeground(new java.awt.Color(0, 0, 0));
        txtIdLayanan.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtIdLayanan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(185, 185, 185)));

        txtTipeLayanan.setBackground(new java.awt.Color(255, 255, 255));
        txtTipeLayanan.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtTipeLayanan.setForeground(new java.awt.Color(0, 0, 0));
        txtTipeLayanan.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTipeLayanan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(185, 185, 185)));

        jLabel27.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Harga");

        txtHarga.setBackground(new java.awt.Color(255, 255, 255));
        txtHarga.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtHarga.setForeground(new java.awt.Color(0, 0, 0));
        txtHarga.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtHarga.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(185, 185, 185)));
        txtHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHargaKeyTyped(evt);
            }
        });

        txtIdJenisLayanan.setBackground(new java.awt.Color(255, 255, 255));
        txtIdJenisLayanan.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtIdJenisLayanan.setForeground(new java.awt.Color(0, 0, 0));
        txtIdJenisLayanan.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtIdJenisLayanan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(185, 185, 185)));

        btnPilihJenis.setBackground(new java.awt.Color(149, 2, 179));
        btnPilihJenis.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPilihJenis.setForeground(new java.awt.Color(255, 255, 255));
        btnPilihJenis.setText(".....");
        btnPilihJenis.setBorderPainted(false);
        btnPilihJenis.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPilihJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihJenisActionPerformed(evt);
            }
        });

        txtJenisLayanan.setBackground(new java.awt.Color(255, 255, 255));
        txtJenisLayanan.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtJenisLayanan.setForeground(new java.awt.Color(0, 0, 0));
        txtJenisLayanan.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtJenisLayanan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(185, 185, 185)));

        btnTambah.setBackground(new java.awt.Color(149, 2, 179));
        btnTambah.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("TAMBAH");
        btnTambah.setBorderPainted(false);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(0, 0, 153));
        btnBatal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setText("BATAL");
        btnBatal.setBorderPainted(false);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormLayout = new javax.swing.GroupLayout(panelForm);
        panelForm.setLayout(panelFormLayout);
        panelFormLayout.setHorizontalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelFormLayout.createSequentialGroup()
                                .addComponent(txtIdJenisLayanan, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPilihJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtJenisLayanan)
                            .addComponent(txtIdLayanan)))
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipeLayanan)
                            .addComponent(txtHarga)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormLayout.createSequentialGroup()
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelFormLayout.setVerticalGroup(
            panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtIdJenisLayanan)
                        .addComponent(btnPilihJenis)))
                .addGap(18, 18, 18)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelFormLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtJenisLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdLayanan, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipeLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnBatal))
                .addContainerGap())
        );

        panelTable.setBackground(new java.awt.Color(255, 255, 255));

        tableData.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Jenis Layanan", "Jenis Layanan", "ID Layanan", "Tipe Layanan", "Nama Layanan", "Harga", "Opsi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableData.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tableData.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataMouseClicked(evt);
            }
        });
        scrollTableData.setViewportView(tableData);
        if (tableData.getColumnModel().getColumnCount() > 0) {
            tableData.getColumnModel().getColumn(0).setMinWidth(125);
            tableData.getColumnModel().getColumn(0).setPreferredWidth(125);
            tableData.getColumnModel().getColumn(0).setMaxWidth(125);
            tableData.getColumnModel().getColumn(1).setMinWidth(175);
            tableData.getColumnModel().getColumn(1).setPreferredWidth(175);
            tableData.getColumnModel().getColumn(1).setMaxWidth(175);
            tableData.getColumnModel().getColumn(2).setMinWidth(125);
            tableData.getColumnModel().getColumn(2).setPreferredWidth(125);
            tableData.getColumnModel().getColumn(2).setMaxWidth(125);
            tableData.getColumnModel().getColumn(3).setMinWidth(125);
            tableData.getColumnModel().getColumn(3).setPreferredWidth(125);
            tableData.getColumnModel().getColumn(3).setMaxWidth(125);
            tableData.getColumnModel().getColumn(5).setMinWidth(100);
            tableData.getColumnModel().getColumn(5).setPreferredWidth(100);
            tableData.getColumnModel().getColumn(5).setMaxWidth(100);
            tableData.getColumnModel().getColumn(6).setMinWidth(200);
            tableData.getColumnModel().getColumn(6).setPreferredWidth(200);
            tableData.getColumnModel().getColumn(6).setMaxWidth(200);
        }

        txtCari.setBackground(new java.awt.Color(255, 255, 255));
        txtCari.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtCari.setForeground(new java.awt.Color(185, 185, 185));
        txtCari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCari.setText("Cari ID Layanan atau Nama Layanan");
        txtCari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(185, 185, 185)));
        txtCari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCariFocusGained(evt);
            }
        });

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollTableData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1120, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCari)
                .addContainerGap())
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTableLayout.createSequentialGroup()
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollTableData, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDataLayout = new javax.swing.GroupLayout(panelData);
        panelData.setLayout(panelDataLayout);
        panelDataLayout.setHorizontalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDataLayout.createSequentialGroup()
                        .addComponent(panelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(panelTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelDataLayout.setVerticalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDataLayout.createSequentialGroup()
                        .addComponent(panelForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(panelData, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        if(btnTambah.getText().equals("TAMBAH")) {
            if(validasiTambahData()) {
                tambahData();
                clearFieldAll();
                tabmodel1.setRowCount(0);
                tampilDataTable();
            }    
        } else {
            ubahData();
            clearFieldAll();
            tabmodel1.setRowCount(0);
            tampilDataTable();
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void txtCariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCariFocusGained
        txtCari.setText("");
        txtCari.setForeground(new Color(0, 0, 0));
        txtCari.setFont(new Font("sansserif", 0, 14));
    }//GEN-LAST:event_txtCariFocusGained

    private void btnPilihJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihJenisActionPerformed
        JenisLayanan jenisLayanan = new JenisLayanan(null, true);
        jenisLayanan.setVisible(true);
        txtIdJenisLayanan.setText(jenisLayanan.modelJenis.getIdJenisLayanan());
        txtJenisLayanan.setText(jenisLayanan.modelJenis.getNamaJenis());
    }//GEN-LAST:event_btnPilihJenisActionPerformed

    private void txtHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaKeyTyped
        char typed = evt.getKeyChar();
        if(!Character.isDigit(typed)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtHargaKeyTyped

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        btnTambah.setText("TAMBAH");
        clearFieldAll();
        txtIdLayanan.setText(controlLayanan.autoID());
        tabmodel1.setRowCount(0);
        tampilDataTable();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void tableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataMouseClicked
        int row = tableData.getSelectedRow();
        piliLayanan(row);
        btnTambah.setText("UBAH");
    }//GEN-LAST:event_tableDataMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnPilihJenis;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel panelData;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelTable;
    private javax.swing.JScrollPane scrollTableData;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIdJenisLayanan;
    private javax.swing.JTextField txtIdLayanan;
    private javax.swing.JTextField txtJenisLayanan;
    private javax.swing.JTextField txtTipeLayanan;
    // End of variables declaration//GEN-END:variables

    
//    Tampil Data Table
    private void tampilDataTable() {
        for(ModelLayanan modelLayanan : controlLayanan.getData()) {
            tabmodel1.addRow(new Object[]{
                modelLayanan.getModelJenisLayanan().getIdJenisLayanan(),
                modelLayanan.getModelJenisLayanan().getNamaJenis(),
                modelLayanan.getIdLayanan(),
                modelLayanan.getTipeLayanan(),
                modelLayanan.getModelJenisLayanan().getNamaJenis()
                .concat(" - ").concat(modelLayanan.getTipeLayanan()),
                modelLayanan.getHarga()
            });
        }
    }
    
//    Tambah Layanan
    private void tambahData() {
        String idJenisLayanan = txtIdJenisLayanan.getText();
        String idLayanan = txtIdLayanan.getText();
        String tipeLayanan = txtTipeLayanan.getText();
        double harga = Double.parseDouble(txtHarga.getText());
        ModelJenisLayanan modelJenis = new ModelJenisLayanan(idJenisLayanan, "");
        ModelLayanan modelLayanan = new ModelLayanan(idLayanan, tipeLayanan, harga, modelJenis);
        controlLayanan.addData(modelLayanan);
        txtIdLayanan.setText(controlLayanan.autoID());
    }
    
//    Ubah Layanan
    private void ubahData() {
        String idJenisLayanan = txtIdJenisLayanan.getText();
        String idLayanan = txtIdLayanan.getText();
        String tipeLayanan = txtTipeLayanan.getText();
        double harga = Double.parseDouble(txtHarga.getText());
        ModelJenisLayanan modelJenis = new ModelJenisLayanan(idJenisLayanan, "");
        ModelLayanan modelLayanan = new ModelLayanan(idLayanan, tipeLayanan, harga, modelJenis);
        controlLayanan.updateData(modelLayanan);
        txtIdLayanan.setText(controlLayanan.autoID());
    }
    
    private void hapusData(int row) {
        String idLayanan = (String) tableData.getValueAt(row, 2);
        ModelLayanan modelLayanan = new ModelLayanan();
        modelLayanan.setIdLayanan(idLayanan);
        if(controlLayanan.validationDelete(modelLayanan)) {
            int confirm = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus layanan ini?", "Konfirmasi", JOptionPane.YES_OPTION);
            if(confirm == 0) {
                if(tableData.isEditing()) {
                    tableData.getCellEditor().stopCellEditing();
                }
                controlLayanan.deleteData(modelLayanan);
                tabmodel1.removeRow(row);
                txtIdLayanan.setText(controlLayanan.autoID());
            }
        }
    }
    
//    Cari Data Layanan
    private void cariDataTable() {
        txtCari.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = txtCari.getText();
                if(text.length() == 0) {
                    tableRowSorter1.setRowFilter(null);
                } else {
                    tableRowSorter1.setRowFilter(RowFilter.regexFilter("(?i)" + text, 2, 4));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = txtCari.getText();
                if(text.length() == 0) {
                    tableRowSorter1.setRowFilter(null);
                } else {
                    tableRowSorter1.setRowFilter(RowFilter.regexFilter("(?i)" + text, 2, 4));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                
            }
        });
    }
    
//    Pilih Layanan
    private void piliLayanan(int row) {
        String idJenisLayanan = (String) tableData.getValueAt(row, 0);
        String jenisLayanan = (String) tableData.getValueAt(row, 1);
        String idLayanan = (String) tableData.getValueAt(row, 2);
        String tipeLayanan = (String) tableData.getValueAt(row, 3);
        double harga = (double) tableData.getValueAt(row, 5);
        txtIdJenisLayanan.setText(idJenisLayanan);
        txtJenisLayanan.setText(jenisLayanan);
        txtIdLayanan.setText(idLayanan);
        txtTipeLayanan.setText(tipeLayanan);
        txtHarga.setText(String.valueOf(harga));
    }
    
    //  Style Table
    private void styleTable(JScrollPane scroll, JTable table, int columnTable) {
        scroll.getViewport().setBackground(new Color(255,255,255));
        JPanel panel = new JPanel();
        panel.setBackground(new Color(255,255,255));
        scroll.setCorner(JScrollPane.UPPER_RIGHT_CORNER, panel);
        scroll.setBorder(new EmptyBorder(5,10,5,10));
        table.setRowHeight(35);        
        table.getTableHeader().setDefaultRenderer(new ModelHeaderTable());
        table.setDefaultRenderer(Object.class, new ModelRenderTable(columnTable));
    }
    
//    event table
    private void eventTable() {
        event = new TableEvent() {
            @Override
            public void onEdit(int row) {
                
            }

            @Override
            public void onDelete(int row) {
                hapusData(row);
            }

            @Override
            public void onView(int row) {
                
            }
        };
        
        tableData.getColumnModel().getColumn(6).setCellRenderer(new TableCellEventRender(false, true, false));
        tableData.getColumnModel().getColumn(6).setCellEditor(new TableCellEditor(event, false, true, false));
    }
    
    private void clearFieldAll() {
        txtIdJenisLayanan.setText("");
        txtJenisLayanan.setText("");
        txtTipeLayanan.setText("");
        txtHarga.setText("");
    }
    
    private void enableField() {
        txtIdJenisLayanan.setEnabled(false);
        txtJenisLayanan.setEnabled(false);
        txtIdLayanan.setEnabled(false);
    }
    
    private boolean validasiTambahData() {
        boolean valid = false;
        if(txtIdJenisLayanan.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Mohon pilih jenis layanan terlebih dahulu");
        } else if(txtTipeLayanan.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Mohon isi tipe layanan ini");
        } else if(txtHarga.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "Mohon isi harga layanan ini");
        } else {
            valid = true;
        }
        return valid;
    }
        
}
